INSERT INTO properties (
  landlord_id, title, description, property_type, bedrooms, bathrooms,
  square_feet, max_guests, base_price_per_night, cleaning_fee, security_deposit,
  address_line1, address_line2, city, state, postal_code, country,
  latitude, longitude, amenities, images, is_featured, is_active, cancellation_policy
) VALUES 
(
  1,
  'Modern Downtown Apartment with City Views',
  'A stunning high-rise apartment in the heart of downtown. Features floor-to-ceiling windows, modern kitchen appliances, a cozy bedroom, and a private balcony overlooking the city skyline. Walk to top restaurants, shops, and public transit in minutes.',
  'apartment',
  1,
  1.0,
  750,
  2,
  150.00,
  45.00,
  150.00,
  '742 Evergreen Terrace',
  'Apt 12B',
  'New York',
  'NY',
  '10001',
  'USA',
  40.7128,
  -74.0060,
  ARRAY['Wifi', 'Air Conditioning', 'Kitchen', 'Gym', 'Elevator', 'Washing Machine'],
  ARRAY['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80'],
  true,
  true,
  'flexible'
),
(
  1,
  'Charming Craftsman House with Private Garden',
  'Beautiful 3-bedroom craftsman house in a quiet, historic neighborhood. Offers spacious bedrooms, a fully equipped gourmet kitchen, cozy fireplace, and a large fenced backyard with a lovely garden. Perfect for families or small groups looking for a peaceful getaway.',
  'house',
  3,
  2.0,
  1800,
  6,
  280.00,
  90.00,
  300.00,
  '123 Maple Street',
  NULL,
  'Seattle',
  'WA',
  '98101',
  'USA',
  47.6062,
  -122.3321,
  ARRAY['Wifi', 'Kitchen', 'Heating', 'Free Parking', 'Dryer', 'Patio/Balcony', 'Dishwasher'],
  ARRAY['https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=800&q=80'],
  true,
  true,
  'moderate'
),
(
  2,
  'Luxury Oceanfront Condo',
  'Wake up to the sound of waves in this spectacular beachfront condo. Features high-end finishes, direct beach access, an infinity pool, and a wrap-around balcony with panoramic ocean views. Fully furnished and equipped with premium amenities for an unforgettable stay.',
  'condo',
  2,
  2.0,
  1200,
  4,
  350.00,
  120.00,
  500.00,
  '1001 Ocean Drive',
  'Suite 405',
  'Miami',
  'FL',
  '33139',
  'USA',
  25.7617,
  -80.1918,
  ARRAY['Wifi', 'Air Conditioning', 'Kitchen', 'Pool', 'Hot Tub', 'Beachfront', 'Elevator'],
  ARRAY['https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80'],
  true,
  true,
  'strict'
),
(
  2,
  'Cozy Loft Studio in Trendy District',
  'Stylish industrial loft studio in the artistic quarter. Featuring exposed brick walls, high ceilings, custom lighting, and clever space-saving furniture. Surrounded by art galleries, microbreweries, and trendy cafes. Ideal for couples or solo travelers.',
  'studio',
  1,
  1.0,
  500,
  2,
  95.00,
  30.00,
  100.00,
  '456 Art Alley',
  'Unit 3A',
  'San Francisco',
  'CA',
  '94103',
  'USA',
  37.7749,
  -122.4194,
  ARRAY['Wifi', 'Air Conditioning', 'Kitchen', 'Heating', 'Washing Machine'],
  ARRAY['https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=800&q=80'],
  false,
  true,
  'flexible'
),
(
  3,
  'Elegant Historic Townhouse',
  'A classic brownstone townhouse combining historic charm with modern upgrades. Boasts high ceilings, original hardwood floors, updated bathrooms, and a modern dining area. Located in a beautiful tree-lined street close to historic landmarks and parks.',
  'townhouse',
  4,
  3.5,
  2200,
  8,
  420.00,
  150.00,
  400.00,
  '88 Beacon Street',
  NULL,
  'Boston',
  'MA',
  '02108',
  'USA',
  42.3601,
  -71.0589,
  ARRAY['Wifi', 'Heating', 'Kitchen', 'Dryer', 'Dishwasher', 'TV', 'Indoor Fireplace'],
  ARRAY['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80'],
  false,
  true,
  'moderate'
);
